---
title: "gapminder-wrangle"
author: "Ruizhe Xu"
date: "2020/7/13"
output: html_document
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Learn 'dplyr' using gapminder dataset
```{r}
gapminder=read_csv("data/gapminder.csv")
head(gapminder)
str(gapminder)
filter(gapminder,lifeExp<29)
filter(gapminder,country=="Mexico")
filter(gapminder,country=="China")
filter(gapminder,country%in%c("Mexico","Peru"))
filter(gapminder,country=="Mexico",year==2002)
```
```{r}
bl=filter(gapminder,country=="Brazil",year>=1987,year<=2007)
mean(bl$lifeExp)
```
```{r}
gap1=dplyr::select(gapminder,year,country,lifeExp)
head(gap1)
```
```{r}
gap2=dplyr::select(gapminder,year:lifeExp)
head(gap2)
```
```{r}
gap3=dplyr::select(gapminder,1,2,4)
head(gap3)
```
```{r}
gap4=dplyr::select(gapminder,-continent,-lifeExp)
head(gap4)
```
```{r}
gap_cambodia=filter(gapminder,country=="Cambodia")
gap_cambodia2=dplyr::select(gap_cambodia,-continent,-lifeExp)
head(gap_cambodia2)
```
```{r}
gapminder%>%head(3)
```
```{r}
gap_cambodia=gapminder %>% 
  filter(country=="Cambodia") %>%
  dplyr::select(-continent,-lifeExp)
```
```{r}
gapminder %>% mutate(gdp=pop*gdpPercap)
```
```{r}
gapminder %>% filter(continent=="Asia",year==2007) %>% mutate(pop1000=pop/1000)
```
```{r}
gapminder %>% 
  filter(year==2002) %>% 
  group_by(continent) %>% 
  mutate(cont_pop=sum(pop))
```
```{r}
gapminder %>% 
  group_by(continent,year) %>% 
  summarize(cont_pop=sum(pop))
```
```{r}
gapminder %>% 
  group_by(continent,year) %>% 
  summarize(cont_pop=sum(pop)) %>% 
  arrange(year)
```
```{r}
gapdesc=gapminder %>% arrange(desc(country))
gapdesc %>% filter(continent=="Asia") %>% group_by(year) %>% summarize(maxlife=max(lifeExp)) %>% ungroup()
```
```{r}
co2=read_csv("data/co2.csv")
co2 %>% head()
dim(co2)
```
```{r}
gap_2007=gapminder %>% filter(year==2007)
gap_2007 %>% dim()
```
```{r}
lj=left_join(gap_2007,co2,by="country")
dim(lj)
```
```{r}
gap_wide=read.csv("data/gapminder_wide.csv")
gapminder=read_csv("data/gapminder.csv")
str(gap_wide)
```
```{r}
gap_long=gap_wide %>% 
  gather(key=obstype_year,value=obs_values,-continent,-country)
```

